# mixture.R -- the native Gaussian-mixture (regime-switching) filter.
#
# mixture_filter() filters a series that switches between a finite set of
# linear-Gaussian regimes, each its own ssm, with a Markov chain governing the
# regime. It is a self-contained Gaussian pseudo-Bayesian filter of order one
# (GPB1; related to but distinct from the IMM filter, which mixes per-regime
# priors under the transition before prediction and carries k Gaussians
# between steps): at each step every regime is advanced by one Kalman
# predict-update from the single mixed prior, the regimes are reweighted by
# their evidence and the regime-transition prior, and the per-regime
# posteriors are collapsed back to one Gaussian. This
# keeps the recursion exact-per-step and linear in the number of regimes, with
# no dependence on a sibling package.
#
# This is the engine kalmix_filter() wraps for the pairs-trading application.

#' A regime-switching mixture filter pass
#'
#' An S7 object holding the output of [mixture_filter()]. The regime
#' probabilities give the filtered posterior over which regime is active at
#' each step; the collapsed state mean and covariance are the
#' mixture-marginalised state estimate.
#'
#' @param regime_prob An `n` by `k` matrix of filtered regime probabilities,
#'   row `t` summing to one over the `k` regimes.
#' @param state_mean An `n` by `m` matrix of collapsed (mixture-marginalised)
#'   state means.
#' @param state_cov A list of `n` collapsed state covariances.
#' @param innovation An `n` by `d` matrix of collapsed one-step innovations:
#'   the observation minus the mixture predictive mean under the chain-prior
#'   regime weights (`NA` at a missing observation).
#' @param innovation_cov A list of `n` collapsed one-step predictive
#'   covariances matching `innovation`.
#' @param innovation_pit For a univariate series, the length-`n`
#'   probability-integral transform of each observation under its one-step
#'   mixture predictive (`NA` at a missing observation; empty for `d > 1`).
#'   This is the exact reference for the adequacy diagnostics, where the
#'   collapsed Gaussian would wrongly fail a well-specified mixture.
#' @param log_lik Numeric scalar — the mixture model log-likelihood.
#' @param n_regimes Integer scalar — the number of regimes `k`.
#'
#' @returns An S7 object of class `regime_fit`.
#' @family state-space
#' @export
regime_fit <- S7::new_class(
  name = "regime_fit",
  package = "kalmix",
  properties = list(
    regime_prob = S7::class_double,
    state_mean = S7::class_double,
    state_cov = S7::class_list,
    innovation = S7::class_double,
    innovation_cov = S7::class_list,
    innovation_pit = S7::new_property(S7::class_double, default = numeric(0L)),
    log_lik = S7::class_double,
    n_regimes = S7::class_integer
  ),
  validator = function(self) {
    if (self@n_regimes < 1L) {
      return("`n_regimes` must be a positive integer")
    }
    NULL
  }
)

#' Regime-switching Gaussian-mixture filter
#'
#' Filters a series generated by a finite set of linear-Gaussian regimes with
#' a Markov chain switching between them. Each regime is supplied as its own
#' [ssm]; the regimes must share a common state and observation dimension. At
#' each step the filter advances every regime by one Kalman predict-and-update
#' from the shared mixed prior, weights the regimes by their one-step evidence
#' and the regime-transition prior, and collapses the per-regime posteriors back
#' to a single Gaussian (a Gaussian pseudo-Bayesian order-one recursion). The
#' returned regime probabilities are the filtered posterior over the active
#' regime.
#'
#' @param models A list of two or more [ssm] objects, one per regime, sharing a
#'   common state and observation dimension.
#' @param y A numeric vector or `n` by `d` matrix of observations. A fully
#'   `NA` entry (row) is a missing observation: every regime runs a
#'   prediction-only step, the regime weights carry the chain prior forward
#'   unchanged and the step adds nothing to the log-likelihood. Partially
#'   missing multivariate rows are refused.
#' @param transition A `k` by `k` regime-transition probability matrix (rows
#'   sum to one), or `NULL` for a default that stays in the current regime with
#'   high probability. Defaults to `NULL`.
#' @param init_prob A length-`k` vector of initial regime probabilities, or
#'   `NULL` for a uniform prior. Defaults to `NULL`.
#'
#' @returns A [regime_fit].
#' @family state-space
#' @seealso [kalman_filter()] for the single-regime base case; [kalmix_filter()]
#'   for the pairs-trading wrapper.
#' @references
#' Bar-Shalom, Y., Li, X. R. and Kirubarajan, T. (2001). *Estimation with
#' Applications to Tracking and Navigation*. Wiley. (GPB and IMM filters.)
#' @export
#' @examples
#' ## Two volatility regimes for a local-level series.
#' calm <- ssm(
#'   transition = 1, observation = 1, state_cov = 0.01, obs_cov = 0.25,
#'   init_state = 0, init_cov = 1
#' )
#' wild <- ssm(
#'   transition = 1, observation = 1, state_cov = 0.01, obs_cov = 4,
#'   init_state = 0, init_cov = 1
#' )
#' set.seed(1)
#' y <- c(rnorm(60, sd = 0.5), rnorm(60, sd = 2))
#' fit <- mixture_filter(list(calm, wild), y)
#' tail(round(fit@regime_prob, 2))
mixture_filter <- function(models,
                           y,
                           transition = NULL,
                           init_prob = NULL) {
  .check_regime_models(models)
  k <- length(models)
  y <- .check_observations(y, models[[1L]])

  transition <- .check_regime_transition(transition, k)
  init_prob <- .check_regime_init(init_prob, k)

  .mixture_filter_native(models, y, transition, init_prob)
}

#' Native Gaussian pseudo-Bayesian (GPB1) regime filter
#'
#' The standalone implementation behind [mixture_filter()]. Carries one mixed
#' Gaussian state across regimes, runs a per-regime Kalman predict-update each
#' step, reweights by evidence and the transition prior, and collapses back to
#' a single regime-conditional Gaussian.
#'
#' @param models A validated list of `k` regime [ssm] objects.
#' @param y The validated `n` by `d` observation matrix.
#' @param transition The `k` by `k` regime-transition matrix.
#' @param init_prob The length-`k` initial regime distribution.
#'
#' @returns A [regime_fit].
#' @noRd
#' @keywords internal
.mixture_filter_native <- function(models, y, transition, init_prob) {
  k <- length(models)
  n <- nrow(y)
  m <- models[[1L]]@state_dim
  d <- models[[1L]]@obs_dim

  regime_prob <- matrix(0, nrow = n, ncol = k)
  state_mean <- matrix(0, nrow = n, ncol = m)
  state_cov <- vector("list", n)
  innovation <- matrix(0, nrow = n, ncol = d)
  innovation_cov <- vector("list", n)
  innovation_pit <- if (d == 1L) rep(NA_real_, n) else numeric(0L)
  log_lik <- 0

  # Shared mixed prior, common to all regimes at entry to each step ----------

  x_mix <- models[[1L]]@init_state
  p_mix <- models[[1L]]@init_cov
  prob <- init_prob

  for (t in seq_len(n)) {

    # Regime-prediction prior: mix the previous posterior through the chain --

    prior <- as.numeric(prob %*% transition)
    means <- vector("list", k)
    covs <- vector("list", k)
    yhats <- vector("list", k)
    preds <- vector("list", k)
    log_w <- numeric(k)
    missing_t <- anyNA(y[t, ])

    for (j in seq_len(k)) {
      a <- .at_step(models[[j]]@transition, t)
      b <- .at_step(models[[j]]@observation, t)
      q <- .at_step(models[[j]]@state_cov, t)
      r <- .at_step(models[[j]]@obs_cov, t)
      ci <- .at_step(models[[j]]@state_intercept, t)
      di <- .at_step(models[[j]]@obs_intercept, t)

      x_pred <- as.numeric(a %*% x_mix) + ci
      p_pred <- a %*% p_mix %*% t(a) + q
      yhats[[j]] <- as.numeric(b %*% x_pred) + di
      preds[[j]] <- b %*% p_pred %*% t(b) + r

      if (missing_t) {
        # Missing observation: prediction-only step in every regime; the data
        # carry no evidence, so the regime weights stay at the chain prior.
        means[[j]] <- x_pred
        covs[[j]] <- .symmetrise(p_pred)
      } else {
        e <- y[t, ] - yhats[[j]]
        s <- preds[[j]]
        s_chol <- .safe_chol(s, "innovation covariance")
        s_inv <- chol2inv(s_chol)
        gain <- p_pred %*% t(b) %*% s_inv

        means[[j]] <- x_pred + as.numeric(gain %*% e)
        covs[[j]] <- .symmetrise(p_pred - gain %*% b %*% p_pred)
        log_w[j] <- log(prior[j] + .Machine$double.xmin) +
          .dmvnorm_log(y[t, ], yhats[[j]], s)
      }
    }

    # Reweight and collapse to one Gaussian ----------------------------------

    if (missing_t) {
      prob <- prior
    } else {
      norm <- .softmax_with_norm(log_w)
      prob <- norm$prob
      log_lik <- log_lik + norm$log_norm
    }

    x_mix <- Reduce(`+`, Map(function(p, mu) p * mu, prob, means))
    p_mix <- Reduce(`+`, Map(function(p, mu, sig) {
      gap <- mu - x_mix
      p * (sig + outer(gap, gap))
    }, prob, means, covs))
    p_mix <- .symmetrise(p_mix)

    # Collapsed one-step innovation: the observation against the mixture
    # predictive under the chain-prior weights, so the moments condition on
    # y_{1:t-1} only (the quantity the adequacy diagnostics whiten).
    y_mix <- Reduce(`+`, Map(function(p, mu) p * mu, prior, yhats))
    s_mix <- Reduce(`+`, Map(function(p, mu, sig) {
      gap <- mu - y_mix
      p * (sig + outer(gap, gap))
    }, prior, yhats, preds))
    innovation[t, ] <- if (missing_t) rep(NA_real_, d) else y[t, ] - y_mix
    innovation_cov[[t]] <- .symmetrise(s_mix)
    if (d == 1L && !missing_t) {
      # Exact one-step probability integral transform under the mixture
      # predictive: uniform when the regime model is correctly specified,
      # the reference the adequacy diagnostics test against.
      innovation_pit[t] <- sum(vapply(seq_len(k), function(j) {
        prior[j] * stats::pnorm(
          y[t, 1L], mean = yhats[[j]][1L], sd = sqrt(preds[[j]][1L, 1L])
        )
      }, numeric(1L)))
    }

    regime_prob[t, ] <- prob
    state_mean[t, ] <- x_mix
    state_cov[[t]] <- p_mix
  }

  regime_fit(
    regime_prob = regime_prob,
    state_mean = state_mean,
    state_cov = state_cov,
    innovation = innovation,
    innovation_cov = innovation_cov,
    innovation_pit = innovation_pit,
    log_lik = log_lik,
    n_regimes = as.integer(k)
  )
}

#' @export
S7::method(print, regime_fit) <- function(x, ...) {
  n <- nrow(x@regime_prob)
  cat(sprintf(
    "<regime_fit>: %d step%s, %d regimes, log-likelihood %.3f\n",
    n, if (n == 1L) "" else "s", x@n_regimes, x@log_lik
  ))
  invisible(x)
}
