# mixture.R -- the native Gaussian-mixture (regime-switching) filter.
#
# mixture_filter() filters a series that switches between a finite set of
# linear-Gaussian regimes, each its own ssm, with a Markov chain governing the
# regime. It is a self-contained Gaussian pseudo-Bayesian filter of order one
# (GPB1; related to but distinct from the IMM filter, which mixes per-regime
# priors under the transition before prediction and carries k Gaussians
# between steps): at each step every regime is advanced by one Kalman
# predict-update from the single mixed prior, the regimes are reweighted by
# their evidence and the regime-transition prior, and the per-regime
# posteriors are collapsed back to one Gaussian. This
# keeps the recursion exact-per-step and linear in the number of regimes, with
# no dependence on a sibling package.
#
# This is the engine kalmix_filter() wraps for the pairs-trading application.

#' A regime-switching mixture filter pass
#'
#' An S7 object holding the output of [mixture_filter()]. The regime
#' probabilities give the filtered posterior over which regime is active at
#' each step; the collapsed state mean and covariance are the
#' mixture-marginalised state estimate.
#'
#' @param regime_prob An `n` by `k` matrix of filtered regime probabilities,
#'   row `t` summing to one over the `k` regimes.
#' @param state_mean An `n` by `m` matrix of collapsed (mixture-marginalised)
#'   state means.
#' @param state_cov A list of `n` collapsed state covariances.
#' @param log_lik Numeric scalar — the mixture model log-likelihood.
#' @param n_regimes Integer scalar — the number of regimes `k`.
#'
#' @returns An S7 object of class `regime_fit`.
#' @family state-space
#' @export
regime_fit <- S7::new_class(
  name = "regime_fit",
  package = "kalmix",
  properties = list(
    regime_prob = S7::class_double,
    state_mean = S7::class_double,
    state_cov = S7::class_list,
    log_lik = S7::class_double,
    n_regimes = S7::class_integer
  ),
  validator = function(self) {
    if (self@n_regimes < 1L) {
      return("`n_regimes` must be a positive integer")
    }
    NULL
  }
)

#' Regime-switching Gaussian-mixture filter
#'
#' Filters a series generated by a finite set of linear-Gaussian regimes with
#' a Markov chain switching between them. Each regime is supplied as its own
#' [ssm]; the regimes must share a common state and observation dimension. At
#' each step the filter advances every regime by one Kalman predict-and-update
#' from the shared mixed prior, weights the regimes by their one-step evidence
#' and the regime-transition prior, and collapses the per-regime posteriors back
#' to a single Gaussian (a Gaussian pseudo-Bayesian order-one recursion). The
#' returned regime probabilities are the filtered posterior over the active
#' regime.
#'
#' @param models A list of two or more [ssm] objects, one per regime, sharing a
#'   common state and observation dimension.
#' @param y A numeric vector or `n` by `d` matrix of observations.
#' @param transition A `k` by `k` regime-transition probability matrix (rows
#'   sum to one), or `NULL` for a default that stays in the current regime with
#'   high probability. Defaults to `NULL`.
#' @param init_prob A length-`k` vector of initial regime probabilities, or
#'   `NULL` for a uniform prior. Defaults to `NULL`.
#'
#' @returns A [regime_fit].
#' @family state-space
#' @seealso [kalman_filter()] for the single-regime base case; [kalmix_filter()]
#'   for the pairs-trading wrapper.
#' @references
#' Bar-Shalom, Y., Li, X. R. and Kirubarajan, T. (2001). *Estimation with
#' Applications to Tracking and Navigation*. Wiley. (GPB and IMM filters.)
#' @export
#' @examples
#' ## Two volatility regimes for a local-level series.
#' calm <- ssm(
#'   transition = 1, observation = 1, state_cov = 0.01, obs_cov = 0.25,
#'   init_state = 0, init_cov = 1
#' )
#' wild <- ssm(
#'   transition = 1, observation = 1, state_cov = 0.01, obs_cov = 4,
#'   init_state = 0, init_cov = 1
#' )
#' set.seed(1)
#' y <- c(rnorm(60, sd = 0.5), rnorm(60, sd = 2))
#' fit <- mixture_filter(list(calm, wild), y)
#' tail(round(fit@regime_prob, 2))
mixture_filter <- function(models,
                           y,
                           transition = NULL,
                           init_prob = NULL) {
  .check_regime_models(models)
  k <- length(models)
  y <- .check_observations(y, models[[1L]])

  transition <- .check_regime_transition(transition, k)
  init_prob <- .check_regime_init(init_prob, k)

  .mixture_filter_native(models, y, transition, init_prob)
}

#' Native Gaussian pseudo-Bayesian (GPB1) regime filter
#'
#' The standalone implementation behind [mixture_filter()]. Carries one mixed
#' Gaussian state across regimes, runs a per-regime Kalman predict-update each
#' step, reweights by evidence and the transition prior, and collapses back to
#' a single regime-conditional Gaussian.
#'
#' @param models A validated list of `k` regime [ssm] objects.
#' @param y The validated `n` by `d` observation matrix.
#' @param transition The `k` by `k` regime-transition matrix.
#' @param init_prob The length-`k` initial regime distribution.
#'
#' @returns A [regime_fit].
#' @noRd
#' @keywords internal
.mixture_filter_native <- function(models, y, transition, init_prob) {
  k <- length(models)
  n <- nrow(y)
  m <- models[[1L]]@state_dim

  regime_prob <- matrix(0, nrow = n, ncol = k)
  state_mean <- matrix(0, nrow = n, ncol = m)
  state_cov <- vector("list", n)
  log_lik <- 0

  # Shared mixed prior, common to all regimes at entry to each step ----------

  x_mix <- models[[1L]]@init_state
  p_mix <- models[[1L]]@init_cov
  prob <- init_prob

  for (t in seq_len(n)) {

    # Regime-prediction prior: mix the previous posterior through the chain --

    prior <- as.numeric(prob %*% transition)
    means <- vector("list", k)
    covs <- vector("list", k)
    log_w <- numeric(k)

    for (j in seq_len(k)) {
      a <- .at_step(models[[j]]@transition, t)
      b <- .at_step(models[[j]]@observation, t)
      q <- .at_step(models[[j]]@state_cov, t)
      r <- .at_step(models[[j]]@obs_cov, t)

      x_pred <- as.numeric(a %*% x_mix)
      p_pred <- a %*% p_mix %*% t(a) + q

      e <- y[t, ] - as.numeric(b %*% x_pred)
      s <- b %*% p_pred %*% t(b) + r
      s_chol <- .safe_chol(s, "innovation covariance")
      s_inv <- chol2inv(s_chol)
      gain <- p_pred %*% t(b) %*% s_inv

      means[[j]] <- x_pred + as.numeric(gain %*% e)
      covs[[j]] <- .symmetrise(p_pred - gain %*% b %*% p_pred)
      log_w[j] <- log(prior[j] + .Machine$double.xmin) +
        .dmvnorm_log(y[t, ], as.numeric(b %*% x_pred), s)
    }

    # Reweight and collapse to one Gaussian ----------------------------------

    norm <- .softmax_with_norm(log_w)
    prob <- norm$prob
    log_lik <- log_lik + norm$log_norm

    x_mix <- Reduce(`+`, Map(function(p, mu) p * mu, prob, means))
    p_mix <- Reduce(`+`, Map(function(p, mu, sig) {
      gap <- mu - x_mix
      p * (sig + outer(gap, gap))
    }, prob, means, covs))
    p_mix <- .symmetrise(p_mix)

    regime_prob[t, ] <- prob
    state_mean[t, ] <- x_mix
    state_cov[[t]] <- p_mix
  }

  regime_fit(
    regime_prob = regime_prob,
    state_mean = state_mean,
    state_cov = state_cov,
    log_lik = log_lik,
    n_regimes = as.integer(k)
  )
}

#' @export
S7::method(print, regime_fit) <- function(x, ...) {
  n <- nrow(x@regime_prob)
  cat(sprintf(
    "<regime_fit>: %d step%s, %d regimes, log-likelihood %.3f\n",
    n, if (n == 1L) "" else "s", x@n_regimes, x@log_lik
  ))
  invisible(x)
}
